spring:
  config:
    import: file:/app/env.properties
  application:
    name: CineMe-BE
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
