spring:
  config:
    import: file:env.properties
  application:
    name: CineMe-BE
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  cache:
    type: redis
    redis:
      time-to-live: 30000 # 5 minutes
  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                redirect-uri: "http://localhost:8080/login/oauth2/code/google"



  jpa:
      hibernate:
          ddl-auto: none
      show-sql: true
#      properties:
#          hibernate:
#            format_sql: true
#            use_sql_comments: true



