spring:
  config:
    import: file:env.properties
  application:
    name: CineMe-BE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10


  jpa:
      hibernate:
          ddl-auto: none
      show-sql: true
      properties:
          hibernate:
          format_sql: true
          use_sql_comments: true
          jdbc:
          batch_size: 100
          order_inserts: true
          generate_statistics: true


